### ISSUE TITLE
大佬，工厂升u8之后服务器重新开服务器连不进去，一直连接超时

### ISSUE THREAD

**Issue by paradise1103** [yingyi666/satisfactory#4]
u7的时候用的大佬写的脚本开的，和朋友一起玩的都没啥问题。这些天升级u8了，重开了服务器和档，就都连不进去了显示超时。整个开服过程没啥问题，查询状态也是在运行，不知道是不是升级了u8有一些服务器配置改了大佬有空看看吗

**Comment by jinzhongjia** [comment]
服务器的状态截图看看

**Comment by paradise1103** [comment]
游戏里看服务器挺正常的，没人第一次登陆过的状态，服务也是运行的，防火墙udp都是开放的



                       
Original Email
                       
                     

Sender:"jinzhongjia"< ***@***.*** &gt;;

Sent Time:2024/1/7 17:43

To:"jinzhongjia/satisfactory"< ***@***.*** &gt;;

Cc recipient:"paradise1103"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [jinzhongjia/satisfactory] 大佬，工厂升u8之后服务器重新开服务器连不进去，一直连接超时 (Issue #4)




 
服务器的状态截图看看

**Comment by paradise1103** [comment]
![2](https://github.com/jinzhongjia/satisfactory/assets/38209201/1d9f5112-00b1-4de1-8b63-f6abb8b7181c)
![3](https://github.com/jinzhongjia/satisfactory/assets/38209201/b5cb3510-c287-4b62-bd91-dbd5ba3a9d55)
![4](https://github.com/jinzhongjia/satisfactory/assets/38209201/cba9e778-7cc6-4b14-832e-0834ba8196ca)
![服务器状态](https://github.com/jinzhongjia/satisfactory/assets/38209201/7b1b2cf7-a952-4978-a995-4148d2e53b77)

**Comment by jinzhongjia** [comment]
你这不都状态出现warning,并且请求epic的api服务器失败了嘛，应该是有啥资源没获取到
我去官方百科看看

**Comment by jinzhongjia** [comment]
查了一下服务器和epic没有任何的api交互，这些请求貌似是嵌入进去的epic的sdk自动请求的，不影响服务器的启动和运行

**Comment by jinzhongjia** [comment]
你有我的实时联系方式吗？
我需要登录服务器看看，光看日志一切正常
qq或者tg啥的，没有的话把你的联系方式直接发到我的邮箱就行，在我github账号首页可以看到

**Comment by paradise1103** [comment]
![1](https://github.com/jinzhongjia/satisfactory/assets/38209201/2f752330-57fa-449a-9269-fa2802d778b8)
是这个页面吗，没找到邮箱

**Comment by paradise1103** [comment]
![1](https://github.com/jinzhongjia/satisfactory/assets/38209201/7183b9cd-51da-41f2-aa20-ed11c5d9a499)

**Comment by jinzhongjia** [comment]
mail@nvimer.org

**Comment by jinzhongjia** [comment]
https://github.com/jinzhongjia/satisfactory/issues/5
